# Generated by Django 6.0.3 on 2026-03-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_recentlyviewed_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviewed',
            name='viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
