# Generated by Django 5.2.7 on 2026-03-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='product_url',
            field=models.URLField(max_length=2000),
        ),
    ]
